/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package edu.ucla.macroscope.textlibrary.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the MacroscopeDocument service. Represents a row in the &quot;TL_MacroscopeDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link edu.ucla.macroscope.textlibrary.model.impl.MacroscopeDocumentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link edu.ucla.macroscope.textlibrary.model.impl.MacroscopeDocumentImpl}.
 * </p>
 *
 * @author dave
 * @see MacroscopeDocument
 * @see edu.ucla.macroscope.textlibrary.model.impl.MacroscopeDocumentImpl
 * @see edu.ucla.macroscope.textlibrary.model.impl.MacroscopeDocumentModelImpl
 * @generated
 */
public interface MacroscopeDocumentModel extends BaseModel<MacroscopeDocument>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a macroscope document model instance should use the {@link MacroscopeDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this macroscope document.
	 *
	 * @return the primary key of this macroscope document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this macroscope document.
	 *
	 * @param primaryKey the primary key of this macroscope document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the document ID of this macroscope document.
	 *
	 * @return the document ID of this macroscope document
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this macroscope document.
	 *
	 * @param documentId the document ID of this macroscope document
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the group ID of this macroscope document.
	 *
	 * @return the group ID of this macroscope document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this macroscope document.
	 *
	 * @param groupId the group ID of this macroscope document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this macroscope document.
	 *
	 * @return the company ID of this macroscope document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this macroscope document.
	 *
	 * @param companyId the company ID of this macroscope document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this macroscope document.
	 *
	 * @return the user ID of this macroscope document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this macroscope document.
	 *
	 * @param userId the user ID of this macroscope document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this macroscope document.
	 *
	 * @return the user uuid of this macroscope document
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this macroscope document.
	 *
	 * @param userUuid the user uuid of this macroscope document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this macroscope document.
	 *
	 * @return the user name of this macroscope document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this macroscope document.
	 *
	 * @param userName the user name of this macroscope document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this macroscope document.
	 *
	 * @return the create date of this macroscope document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this macroscope document.
	 *
	 * @param createDate the create date of this macroscope document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this macroscope document.
	 *
	 * @return the modified date of this macroscope document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this macroscope document.
	 *
	 * @param modifiedDate the modified date of this macroscope document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the content of this macroscope document.
	 *
	 * @return the content of this macroscope document
	 */
	public Blob getContent();

	/**
	 * Sets the content of this macroscope document.
	 *
	 * @param content the content of this macroscope document
	 */
	public void setContent(Blob content);

	/**
	 * Returns the title of this macroscope document.
	 *
	 * @return the title of this macroscope document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this macroscope document.
	 *
	 * @param title the title of this macroscope document
	 */
	public void setTitle(String title);

	/**
	 * Returns the author of this macroscope document.
	 *
	 * @return the author of this macroscope document
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this macroscope document.
	 *
	 * @param author the author of this macroscope document
	 */
	public void setAuthor(String author);

	/**
	 * Returns the collection of this macroscope document.
	 *
	 * @return the collection of this macroscope document
	 */
	@AutoEscape
	public String getCollection();

	/**
	 * Sets the collection of this macroscope document.
	 *
	 * @param collection the collection of this macroscope document
	 */
	public void setCollection(String collection);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MacroscopeDocument macroscopeDocument);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MacroscopeDocument> toCacheModel();

	@Override
	public MacroscopeDocument toEscapedModel();

	@Override
	public MacroscopeDocument toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}